### ISSUE TITLE
OpenSSL::Cipher::CipherError

### ISSUE THREAD

**Issue by ternes3** [railslove/epics#37]
Hello again :-),
now, after the initialization process finished, I try to fetch the available methods of my bank. 
But when i try to get e with `e = Epics::Client.new(keys, 'passphrase', 'url', 'host', 'user', 'partner')` it run into following error:  OpenSSL::Cipher::CipherError

any ideas?

thanks
ternes3

**Comment by kangguru** [comment]
hejho,

can you please try to answer the following questions so we can better
triangulate the error.

what bank are you working with?

can you provide the complete stacktrace?

did you save the keyfile after fetching the public keys of the bank via HPB?

**Comment by ternes3** [comment]
hey, 
the bank is called >>Kreissparkasse Mayen<<,
````
epics (1.4.0) lib/epics/client.rb:240:in `final'
epics (1.4.0) lib/epics/client.rb:240:in `decrypt'
epics (1.4.0) lib/epics/client.rb:215:in `block in extract_keys'
epics (1.4.0) lib/epics/client.rb:214:in `each'
epics (1.4.0) lib/epics/client.rb:214:in `each_with_object'
epics (1.4.0) lib/epics/client.rb:214:in `extract_keys'
epics (1.4.0) lib/epics/client.rb:12:in `initialize'
app/controllers/fetchmethod_controller.rb:8:in `new'
app/controllers/fetchmethod_controller.rb:8:in `index'
actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
```
Thats currently the point where I am, i try to fetch the public keys of the bank to save them for later use.

```
...
key = File.read("key/key.key")
    e = Epics::Client.new(key, ']4HsXTU*$Wt;Uz]&DBsf)&{&h~dK33R9s$&{EG9r8#gLn%zQpQW3Cz{Lh]/,Hz7ZjUCP&,5[%?q_XNQ?', "https://rp1ebics.sparkasse-banking.de/ebicsweb/ebicsweb", "HOST", "Teilnehmer-ID", "Kunden-ID") #the passphrase is just like the one i use, its not the one I use in production.  ERROR LINE
    e.HPB 
    e.save_keys(path)
...
```

**Comment by kangguru** [comment]
hm, and you can find proper keys in the file?

it should look something like that:

```json
{
  "A006": "XXX",
  "X002": "YYY", 
  "E002": "ZZZ"
}
```

**Comment by ternes3** [comment]
Yes, it looks like this. 
XXX, YYY, ZZZ have a length of 2252 chars.

**Comment by kangguru** [comment]
thats fine so far. what is the exception message you get?

`bad decrypt`? i'd assume that there maybe a issue with the key you're using. I've no problems with the one you're giving as example. 

do you have the `#setup` command in some history (maybe you missed to copy a character ), or how is the passphrase created?

**Comment by ternes3** [comment]
hey, 
the solution is simple, my used key is in setup with "" surrounded, in .new with ''. Inside the string is \N so this trigger the trouble. Now im using everywhere "" and it works :) 

thanks for the help

**Comment by kangguru** [comment]
:) interesting, but yea. newlines are escaped differently.

cool that it now works!
